---
title: "Le point sur le risque Xylella fastidiosa en France"
slug: "risqueXf"
author: "Jean-Pierre Rossi"
date: 2019-11-27T21:13:14-05:00
categories: ["Santé des plantes"]
tags: ["risque", "Xylella fastidiosa", "insecte vecteur", "Philaenus spumarius"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Depuis sa détection en France en 2015, la bactérie *Xylella fastidiosa* a fait couler beaucoup d’encre ! Dans un article récent, notre équipe fait le point sur la situation et propose un cadre conceptuel original pour évaluer le risque associé à cet organisme ainsi qu'à d’autres espèces potentiellement responsables de dégâts en forêt, arboriculture, grandes cultures ou dans la filière ornementale.

Le texte fait suite à un exposé présenté dans le cadre de la journée thématique intitulée « Gestion du risque en agriculture » organisée par l’Inra le 27 juin 2019 à Paris dans le cadre des Carrefours de l'Innovation Agronomique (https://www6.inra.fr/ciag/CIAg-Agriculture/Gestion-du-risque-en-agriculture).

L’article est disponible sur le site de l’institut : https://www6.inra.fr/ciag/content/download/6768/49394/file/Vol77-10-Rossi%20et%20al.pdf

Bonne lecture !

**Référence**

Rossi J.-P., Godefroid M., Burban C., Chartois M., Mesmin X., Farigoule P., Streito J.-C., Cruaud A., Rasplus J.-Y., 2019. Evaluer le risque associé à des agents phytopathogènes émergents transmis par des insectes : le cas de *Xylella fastidiosa*.
Innovations Agronomiques 77, 87-97.
